tcp_stream: 'clever'
reset_pools: true
generate_meta_files: false
search_all_protocols: false
rules:
#  -
#      field: http.host
#      modifier: HttpTextRandom
#      exclude:
#        value: ['Host: www.foo.com']
#        validation: 'prefix'
#      include: []
#      additional:
#          foo: 'bar'
#  -
#      field: ip.dst
#      modifier: IPRandom
#      include: []
#      exclude: []
#
#  -
#      field: ip.src
#      modifier: IPRandom
#      include: []
#      exclude: []

  -
      field: udp.srcport
      modifier: NumberRandom
      value_group: 'src_port'
      include: []
      exclude: []
  -
      field: udp.dstport
      modifier: NumberRandom
      value_group: 'src_port'
      include: []
      exclude: []

  -
      field: tcp.srcport
      modifier: NumberRandom
      value_group: 'src_port'
      include: []
      exclude: []
  -
      field: tcp.dstport
      modifier: NumberRandom
      value_group: 'src_port'
      include: []
      exclude: []
#
#  -
#      field: tls.handshake.certificates
#      modifier: ClearMarker
#      value: 40
#      include: []
#      exclude: []
#  -
#      field: ip.src
#      method: IPMarkerPreserveNPrefix
#      value_group: 'IP'
#      params:
#          value:
#            value: '255.255'
#            preserve: 16
#          exclude: []
#          include: []
#          additional:
#            validation: 'prefix'
#            mine: 'Hello'
#            you: 'doing'
#            packet: 3
#  -
#      field: ip.src
#      method: IPMarker
#      params:
#          value: '255.255.255.255'
#          exclude: []
#          include: []
#          additional:
#            mine: 'Hello'
#            you: 'doing'
#            packet: 3
#  -
#      field: dns.a
#      method: ip_random
#      params:
#          value: 'pn.yoloswagger.ns.com'
#          exclude: []
#          include: []
#          additional:
#            mine: 'Hello'
#            you: 'doing'
#            packet: 3
#  - field: dns.qry.type
#    method: default_number_marker
#    params:
#      value: 2
#      exclude: []
#      include: []
#      additional:
#        mine: 'Hello'
#        you: 'doing'
#        packet: 3
#  -
#      field: frame.time_epoch
#      method: FrameTimeMarkerIncrement
#      params:
#          value: '0.100000'
#          exclude: []
#          include: []
#          additional:
#            mine: 'Hello'
#            you: 'doing'
#            packet: 3
#  -
#      field: frame.time_epoch
#      method: time_stamp_clear_and_increment
#      params:
#          value: '0.500000'
#          exclude: []
#          include: []
#          additional:
#            mine: 'Hello'
#            you: 'doing'
#            packet: 3
#  -
#      field: tls.handshake.server_point
#      method: default_clear_all
#      params:
#          value: ''
#          exclude: []
#          include: []
##  -
#      field: tls.record
#      method: default_clear_all
#      params:
#          value: ''
#          exclude: []
#          include: []
#  -
#      field: http.request.line
##      method: modify_field
#      method: http_random_text_preserve_prefix
##      method: default_http_marker_preserve_prefix
##      class: custom_xml_modifier.CustomXMLModifier
#      params:
#          value: 'PN EVERYWHERE'
#          exclude: []
#          include: []
#  -
#      field: ssdp.http.server
#      method: http_random_text_preserve_prefix
#      params:
#          value: ''
#          exclude: []
#          include: []
#  -
#      field: tls.record.content_type
#      method: default_number_marker
#      params:
#          value: '23'
#          exclude: []
#          include: []
#
#  - field: eth.src
#    method: MACRandomPreserveFlags
#    value_group: 'ETH'
#    params:
#      value: 'ff'
#      exclude: []
#      include: []
#      additional:
#        validation: 'suffix'
#
#  - field: eth.dst
#    method: MACRandomPreserveFlags
#    value_group: 'ETH'
#    params:
#      value: 'ff'
#      exclude: []
#      include: []
#      additional:
#        validation: 'suffix'
#  -
#      field: tls.handshake
#      method: default_clear_all
#      params:
#          value: '23'
#          exclude: []
#          include: []
##  -
##      field: ip.version
##      method: default_number_marker
##      params:
##          value: '8'
##          exclude: []
##          include: []
#  -
#      field: http.host
#      method: HttpTextMarker
#      params:
#          value: 'Host: PN mega dloooooooooohy texxt'
#          exclude: []
#          include: []
#  -
#      field: http.server
#      method: default_http_marker
#      params:
#          value: 'Server: CHANGE TEST'
#          exclude: []
#          include: []
#  -
#      field: tls.record.version
#      method: default_number_marker
#      params:
#          value: '256'
#          exclude: []
#  -
#      field: dhcp.type
#      method: default_number_marker
#      params:
#          value: '2'
#          exclude: []
#          include: []
#  -
#      field: dhcp.ip.your
#      method: ip_marker
#      value_group: 'IP'
#      params:
#          value: '255.255.255.255'
#          exclude: []
#          include: []
#  -
#      field: arp.dst.hw_mac
#      method: eth_marker
#      value_group: 'ETH'
#      params:
#          value: "ff:ff:ff:ff:ff:ff"
#          exclude: []
#          include: []
#  -
#      field: dhcp.hw.mac_addr
#      method: eth_marker
#      value_group: 'ETH1'
#      params:
#          value: "ff:ff:ff:ff:ff:ff"
#          exclude: []
#          include: []
#  -
#      field: eth.src
#      method: eth_marker
#      value_group: 'KVAK'
#      params:
#          value: "ff:ff:ff:ff:ff:ff"
#          exclude: []
#          include: []
#  -
#      field: ip.src
#      method: ip_marker_preserve_n_suffix
#      value_group: 'IP'
#      params:
#        value:
#          value: '255.255'
#          preserve_length: 16
#        exclude: []
#        include: []
#  -
#      field: ip.src
#      method: IPMarker
#      value_group: 'IP'
#      params:
#        value: '244.244.244.244'
#        exclude: ['192.168.0.0']
#        include: ['192.168.0.0/16']
#  -
#      field: ip.dst
#      method: ip_marker_preserve_n_suffix
#      value_group: 'IP'
#      params:
#        value:
#          value: '255.255'
#          preserve_length: 16
#        exclude: []
#        include: []
#  -
#      field: udp.srcport
#      method: port_random_preserve_group
#      params:
#        value: 8
#        exclude: []
#        include: []
#  -
#      field: udp.dstport
#      method: port_random_preserve_group
#      params:
#        value: 8
#        exclude: []
#        include: []
#  -
#      field: ip.dst
#      method: ip_marker
#      value_group: 'IP2'
#      params:
#        value: '255.255.255.255'
#        exclude: ['192.168.0.10/16']
#        include: ['192.168.0.10/16']
#      field: ip.dst
#      method: ip_random_preserve_class
#      value_group: 'IP2'
#      params:
#        value: "255.255.255.255"
#        exclude: []
#        include: []
#  -
#      field: ip.dst.adadadada
#      method: ip_marker
#      value_group: 'IP'
#      params:
#        value: "255.255.255.255"
#        exclude: []
#        include: []
#  -
#      field: ip.dst
#      method: ip_marker
#      namisto shared_with pridat groupy
#      shared_with: eth.ip.src
#      exclude ma nejvyssi prioritu
#      pokud exclude zakaze, include to nepovoli
#      params:
#        value: "255.255.255.255"
#        exclude: ["192.168.1.1/8", "138.201.81.199"]
#        pridat include (komunikace pouze na specificke siti)
# pridat suffix/preffix pro definici zachovavani prefix//suffix pro jine metody nez marker
# vzdalenost IP address 1.1.1.2 - 1
# metriky pro IP addresy - obecne anonymiazce - na zaklade toho si domluvit, ktere budeme delat a ktere ne
# 6235RF - podivat se
# podivat se opet na tshark/pyshark a praci s byty
# expotovat jako json a pak s nim pracovat a modifikovat bytove pole
#
#  -
#      field: eth.ip.sad
#      method: ip_marker
#      params:
#        value: "255.255.255.255"
#        exclude: []
