tcp_stream: 'clever'
reset_pools: true
generate_meta_files: true
search_all_protocols: false
rules:
  -
      field: tcp.srcport
      modifier: NumberRandom
      include: []
      exclude: []
      value_group: 'PORTY'

  -
      field: tcp.dstport
      modifier: NumberRandom
      include: []
      exclude: []
      value_group: 'PORTY'
