verbose: false
tcp_stream: 'clever'
reset_pools: true
generate_meta_files: true
files:
  - "dhcp.pcap"
  - "../dataset/single_pcaps/http/http.pcap"
  - "../dataset/single_pcaps/http/test.pcap"
#  - "tcp_tls_ignored_record.pcap"
#  - "tcp_retransmission.pcap"
  - "tcp_missing_middle_segment.pcap"
#  - "segmented_tls_missing_last.pcap"
#  - "segmented_tls.pcap"
#  - "merged.pcap"
#  - "tcp_middle.pcap"
#  - "test.pcap"
#  - "../dataset/single_pcaps/big_test.pcap"
#  - "../dataset/single_pcaps/mega_segmented.pcap"
#  - "../dataset/single_pcaps/mmega.pcap"
#  - "weird_tls.pcap"
#  - "segmented.pcap"
#  - "seg.pcap"
#  - "../dataset/single_pcaps/multiple_records.pcap"
#  - "../dataset/single_pcaps/the_biggest.pcap"
#  - "../dataset/single_pcaps/bbig.pcap"
#  - "../dataset/single_pcaps/who_knows.pcap"
#  - "../dataset/single_pcaps/huh.pcap"
#  - "../dataset/single_pcaps/http/http.pcap"
#  - "../dataset/single_pcaps/http/http-chunked-gzip.pcap"
#  - "../dataset/single_pcaps/http/segmented_html.pcap"
rules:
#  -
#      field: frame.time_epoch
#      method: default_time_marker
#      params:
#          value: '1577912212.0'
#          exclude: []
#          include: []
#  -
#      field: tls.handshake
#      method: default_clear_all
#      params:
#          value: ''
#          exclude: []
#          include: []
#  -
#      field: tls.record
#      method: default_clear_all
#      params:
#          value: ''
#          exclude: []
#          include: []
  -
      field: http.request.line
#      method: modify_field
      method: http_random_text_preserve_prefix
#      method: default_http_marker_preserve_prefix
#      class: custom_xml_modifier.CustomXMLModifier
      params:
          value: 'PN EVERYWHERE'
          exclude: []
          include: []
#  -
#      field: http.server
#      method: default_http_marker
#      params:
#          value: 'Server:  Runs on COVID-19'
#          exclude: []
#          include: []
#  -
#      field: tls.record.content_type
#      method: default_number_marker
#      params:
#          value: '23'
#          exclude: []
#          include: []

#  - field: eth.src
#    method: do_not_modify
#    value_group: 'ETH'
#    params:
#      value: "ff:ff:ff:ff:ff:ff"
#      exclude: []
#      include: []
#  -
#      field: tls.handshake
#      method: default_clear_all
#      params:
#          value: '23'
#          exclude: []
#          include: []
##  -
##      field: ip.version
##      method: default_number_marker
##      params:
##          value: '8'
##          exclude: []
##          include: []
#  -
#      field: http.host
#      method: default_http_marker
#      params:
#          value: 'Host: PN mega dloooooooooohy texxt'
#          exclude: []
#          include: []
#  -
#      field: http.server
#      method: default_http_marker
#      params:
#          value: 'Server: CHANGE TEST'
#          exclude: []
#          include: []
###  -
###      field: tls.record.version
###      method: default_number_marker
###      params:
###          value: '256'
###          exclude: []
#  -
#      field: dhcp.type
#      method: default_number_marker
#      params:
#          value: '2'
#          exclude: []
#          include: []
#  -
#      field: dhcp.ip.your
#      method: ip_marker
#      value_group: 'IP'
#      params:
#          value: '255.255.255.255'
#          exclude: []
#          include: []
  -
      field: eth.dst
      method: eth_marker
      value_group: 'ETH'
      params:
          value: "ff:ff:ff:ff:ff:ff"
          exclude: []
          include: []
#  -
#      field: eth.src
#      method: eth_marker
#      value_group: 'KVAK'
#      params:
#          value: "ff:ff:ff:ff:ff:ff"
#          exclude: []
#          include: []
  -
      field: ip.src
      method: ip_prefix_preservation
      value_group: 'IP'
      params:
        value: "255.255.255.255"
        exclude: []
        include: []
  -
      field: ip.dst
      method: ip_random
      value_group: 'IP2'
      params:
        value: "255.255.255.255"
        exclude: []
        include: []
#  -
#      field: ip.dst.adadadada
#      method: ip_marker
#      value_group: 'IP'
#      params:
#        value: "255.255.255.255"
#        exclude: []
#        include: []
#  -
#      field: ip.dst
#      method: ip_marker
#      namisto shared_with pridat groupy
#      shared_with: eth.ip.src
#      exclude ma nejvyssi prioritu
#      pokud exclude zakaze, include to nepovoli
#      params:
#        value: "255.255.255.255"
#        exclude: ["192.168.1.1/8", "138.201.81.199"]
#        pridat include (komunikace pouze na specificke siti)
# pridat suffix/preffix pro definici zachovavani prefix//suffix pro jine metody nez marker
# vzdalenost IP address 1.1.1.2 - 1
# metriky pro IP addresy - obecne anonymiazce - na zaklade toho si domluvit, ktere budeme delat a ktere ne
# 6235RF - podivat se
# podivat se opet na tshark/pyshark a praci s byty
# expotovat jako json a pak s nim pracovat a modifikovat bytove pole
#
#  -
#      field: eth.ip.sad
#      method: ip_marker
#      params:
#        value: "255.255.255.255"
#        exclude: []
