verbose: false
files:
#  - "dhcp.pcap"
#  - "segmented_tls.pcap"
#  - "merged.pcap"
#  - "test.pcap"
#  - "../dataset/single_pcaps/big_test.pcap"
#  - "weird_tls.pcap"
#  - "segmented.pcap"
#  - "seg.pcap"
#  - "../dataset/single_pcaps/multiple_records.pcap"
#  - "../dataset/single_pcaps/the_biggest.pcap"
#  - "../dataset/single_pcaps/bbig.pcap"
#  - "../dataset/single_pcaps/huh.pcap"
#  - "../dataset/single_pcaps/http/http.pcap"
  - "../dataset/single_pcaps/http/http-chunked-gzip.pcap"
rules:
  -
      field: tls.record.content_type
      method: default_number_marker
      params:
          value: '21'
          exclude: []
  -
      field: http.host
      method: default_text_marker
      params:
#        How to new line?
          value: 'Hello from PN\r\n'
          exclude: []
  -
      field: http.server
      method: default_text_marker
      params:
#        How to new line?
          value: 'PN SRVR\r\n'
          exclude: []
#  -
#      field: tls.record.version
#      method: default_number_marker
#      params:
#          value: '256'
#          exclude: []
  -
      field: dhcp.type
      method: default_number_marker
      params:
          value: '2'
          exclude: []
  -
      field: dhcp.ip.your
      method: ip_marker_shark
      params:
          value: '255.255.255.255'
          exclude: []
  -
      field: eth.dst
      method: eth_marker_shark
      params:
          value: "ff:ff:ff:ff:ff:ff"
          exclude: []
  -
      field: eth.src
      method: eth_marker_shark
      params:
          value: "ff:ff:ff:ff:ff:ff"
          exclude: []
  -
      field: ip.src
      method: ip_marker_shark
      params:
        value: "255.255.255.255"
        exclude: []
  -
      field: ip.dst
      method: ip_marker_shark
      params:
        value: "255.255.255.255"
        exclude: []
#  -
#      field: ip.dst
#      method: ip_marker
#      namisto shared_with pridat groupy
#      shared_with: eth.ip.src
#      exclude ma nejvyssi prioritu
#      pokud exclude zakaze, include to nepovoli
#      params:
#        value: "255.255.255.255"
#        exclude: ["192.168.1.1/8", "138.201.81.199"]
#        pridat include (komunikace pouze na specificke siti)
# pridat suffix/preffix pro definici zachovavani prefix//suffix pro jine metody nez marker
# vzdalenost IP address 1.1.1.2 - 1
# metriky pro IP addresy - obecne anonymiazce - na zaklade toho si domluvit, ktere budeme delat a ktere ne
# 6235RF - podivat se
# podivat se opet na tshark/pyshark a praci s byty
# expotovat jako json a pak s nim pracovat a modifikovat bytove pole
#
#  -
#      field: eth.ip.sad
#      method: ip_marker
#      params:
#        value: "255.255.255.255"
#        exclude: []
